name: StrakaPowers
main: omari.SuperPowers.SuperPowers
version: 0.1

commands:
  cat:
    description: butts
  avatarState:
    description: Turn into dah avatah!
  airBend:
    description: Fly!
  earthBend:
    description: Earth walls!
  waterBend:
    description: Water columns!
  fireBend:
    description: Shoot fire!
  metalBend:
    description: Iron shield!
  lavaBend:
    description: Iron shield!
  flash:
    description: Super speed dude.
  shazam:
    description: Gives you the powers of Shazam!
  kazaam:
    description: Rains food.
  debug:
    description: Debugs stuff.