name: HelloWorld
main: com.peteranpham.bukkitone.Tutorial
version: 1.0

commands:
  cat:
    description: butts
  rain:
    description: butts
  flash:
    description: Super speed dude.
  shazam:
    description: Gives you the powers of Shazam!