name: StrakaPowers
main: omari.SuperPowers.SuperPowers
version: 0.1

commands:
  cat:
    description: butts
  glass:
    description: butts
  flash:
    description: Super speed dude.
  shazam:
    description: Gives you the powers of Shazam!
  kazaam:
  	description: Rains food.